---
- name: Creating build directories for each host
  hosts: junos_all
  connection: ansible.builtin.local
  gather_facts: no
  tasks:
    - name: Remove host build temp directory
      ansible.builtin.file: 
        path: "{{ build_dir }}"
        state: absent
    - name: Create host build temp directory
      ansible.builtin.file: 
        path: "{{ build_dir }}"
        state: directory

- name: Creating render directory for complete config files
  hosts: localhost
  connection: ansible.builtin.local
  gather_facts: no
  tasks:
    - name: Remove render directory
      ansible.builtin.file:
        path: "{{ render_dir }}"
        state: absent
    - name: Create render directory
      ansible.builtin.file: 
        path: "{{ render_dir }}"
        state: directory